# Generated by Django 3.2.9 on 2021-12-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPrenomEn', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismedAccueil',
            fields=[
                ('NomOrganisme', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('typeOr', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('matricule', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('NomStagiaire', models.CharField(max_length=15)),
                ('PrenomStagiaire', models.CharField(max_length=30)),
                ('NivEtude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeStage',
            fields=[
                ('NomType', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('NivEtude', models.IntegerField()),
                ('periode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomStage', models.CharField(max_length=40)),
                ('Sujet', models.CharField(max_length=60)),
                ('Organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.organismedaccueil')),
                ('TypeStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.typestage')),
            ],
        ),
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPrenomPro', models.CharField(max_length=40)),
                ('Organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.organismedaccueil')),
            ],
        ),
        migrations.CreateModel(
            name='Faire_Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NivEtude', models.IntegerField()),
                ('AnneeCourante', models.IntegerField(default=2021)),
                ('Groupe', models.IntegerField()),
                ('Encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.encadrant')),
                ('Organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.organismedaccueil')),
                ('Promoteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.promoteur')),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.stage')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.stagiaire')),
            ],
            options={
                'unique_together': {('matricule', 'NivEtude', 'AnneeCourante')},
            },
        ),
    ]
