# Generated by Django 3.2.9 on 2021-12-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0002_auto_20211227_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestage',
            name='periode',
            field=models.CharField(max_length=30),
        ),
    ]
