# Generated by Django 3.2.9 on 2021-12-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0003_alter_typestage_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Sujet',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
