# Generated by Django 3.2.9 on 2021-12-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0004_alter_stage_sujet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagiaire',
            options={'ordering': ['NomStagiaire']},
        ),
    ]
