# Generated by Django 3.2.9 on 2021-12-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0005_alter_stagiaire_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagiaire',
            options={'ordering': ['NivEtude']},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='Sujet',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='TypeStage',
        ),
        migrations.AddField(
            model_name='faire_stage',
            name='Sujet',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='NivEtude',
            field=models.CharField(default='1', max_length=3),
        ),
        migrations.DeleteModel(
            name='TypeStage',
        ),
    ]
