# Generated by Django 3.2.9 on 2021-12-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0007_alter_encadrant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoteur',
            options={'ordering': ['NomPrenomPro']},
        ),
    ]
