# Generated by Django 3.2.9 on 2021-12-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0008_alter_promoteur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faire_stage',
            name='Sujet',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
