# Generated by Django 3.2.9 on 2021-12-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0009_alter_faire_stage_sujet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='NivEtude',
            field=models.CharField(choices=[('1', 'cp1'), ('3', 'cs1'), ('5', 'cs3')], max_length=4),
        ),
    ]
