# Generated by Django 3.2.9 on 2021-12-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0010_alter_stage_nivetude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='NivEtude',
            field=models.IntegerField(choices=[(1, 'CP1'), (3, 'CS1'), (5, 'CS3')]),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='NivEtude',
            field=models.IntegerField(choices=[(1, 'CP1'), (2, 'CP2'), (3, 'CS1'), (4, 'CS2'), (5, 'CS3')]),
        ),
    ]
