# Generated by Django 3.2.9 on 2021-12-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0012_alter_faire_stage_nivetude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faire_Stage',
            new_name='Fiche_Stage',
        ),
        migrations.RenameModel(
            old_name='OrganismedAccueil',
            new_name='Organisme',
        ),
    ]
