# Generated by Django 4.0 on 2022-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0013_auto_20211230_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche_stage',
            name='AnneeCourante',
            field=models.IntegerField(default=2022),
        ),
    ]
