# Generated by Django 3.2.9 on 2022-01-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0014_alter_fiche_stage_anneecourante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='matricule',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
