# Generated by Django 4.0 on 2022-01-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0015_alter_stagiaire_matricule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fiche_stage',
            unique_together={('NivEtude', 'AnneeCourante')},
        ),
        migrations.CreateModel(
            name='Matricule3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Matricule2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Matricule1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.stagiaire')),
            ],
        ),
        migrations.RemoveField(
            model_name='fiche_stage',
            name='matricule',
        ),
        migrations.AddField(
            model_name='fiche_stage',
            name='Matricule1',
            field=models.ForeignKey(default=646874, on_delete=django.db.models.deletion.CASCADE, to='AppGestion.matricule1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche_stage',
            name='Matricule2',
            field=models.ForeignKey(default=5458451, on_delete=django.db.models.deletion.CASCADE, to='AppGestion.matricule2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche_stage',
            name='Matricule3',
            field=models.ForeignKey(default=556321, on_delete=django.db.models.deletion.CASCADE, to='AppGestion.matricule3'),
            preserve_default=False,
        ),
    ]
