# Generated by Django 4.0 on 2022-01-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0016_alter_fiche_stage_unique_together_matricule3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricule2',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='matricule3',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='fiche_stage',
            name='Matricule1',
        ),
        migrations.RemoveField(
            model_name='fiche_stage',
            name='Matricule2',
        ),
        migrations.RemoveField(
            model_name='fiche_stage',
            name='Matricule3',
        ),
        migrations.AddField(
            model_name='fiche_stage',
            name='etudiantPremier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Fiche_Stage', to='AppGestion.stagiaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche_stage',
            name='etudiantdeux',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='AppGestion.stagiaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche_stage',
            name='etudianttroi',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='AppGestion.stagiaire'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Matricule1',
        ),
        migrations.DeleteModel(
            name='Matricule2',
        ),
        migrations.DeleteModel(
            name='Matricule3',
        ),
    ]
