# Generated by Django 4.0 on 2022-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0017_remove_matricule2_matricule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fiche_stage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fiche_stage',
            name='Groupe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='fiche_stage',
            unique_together={('Groupe', 'NivEtude', 'AnneeCourante')},
        ),
    ]
