# Generated by Django 3.2.9 on 2022-01-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0018_alter_fiche_stage_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiche_stage',
            old_name='etudiantPremier',
            new_name='Etudiant1',
        ),
        migrations.RenameField(
            model_name='fiche_stage',
            old_name='etudiantdeux',
            new_name='Etudiant2',
        ),
        migrations.RenameField(
            model_name='fiche_stage',
            old_name='etudianttroi',
            new_name='Etudiant3',
        ),
        migrations.AlterUniqueTogether(
            name='fiche_stage',
            unique_together={('Groupe', 'AnneeCourante')},
        ),
    ]
