# Generated by Django 3.2.9 on 2022-01-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0019_auto_20220119_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche_stage',
            name='Sujet',
            field=models.TextField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
