# Generated by Django 3.2.9 on 2022-02-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0023_auto_20220208_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche_stage',
            name='NivEtude',
            field=models.IntegerField(choices=[(1, 'CP1'), (3, 'CS1'), (5, 'CS3')]),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='typeOr',
            field=models.IntegerField(choices=[(1, 'partenaire'), (0, 'non partenaire')]),
        ),
        migrations.AlterField(
            model_name='stage',
            name='NivEtude',
            field=models.IntegerField(choices=[(1, 'CP1'), (3, 'CS1'), (5, 'CS3')]),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='NivEtude',
            field=models.IntegerField(choices=[(1, 'CP1'), (2, 'CP2'), (3, 'CS1'), (4, 'CS2'), (5, 'CS3')]),
        ),
    ]
