# Generated by Django 3.2.9 on 2022-02-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0024_auto_20220208_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='typeOr',
            field=models.IntegerField(choices=[(1, 'partenaire'), (0, 'nonPartenaire')]),
        ),
    ]
