# Generated by Django 3.2.9 on 2022-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0025_alter_organisme_typeor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='typeOr',
            field=models.CharField(choices=[('partenaire', 'partenaire'), ('nonPartenaire', 'nonPartenaire')], max_length=30),
        ),
    ]
