# Generated by Django 3.2.9 on 2022-02-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0027_auto_20220209_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche_stage',
            name='Sujet',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
